service:
  discovery:
    hostname: ${DISCOVERY_HOSTNAME}
    port: ${DISCOVERY_PORT}
  auth:
    hostname: ${AUTH_SERVICE_HOSTNAME}
  mysql:
    hostname: ${MYSQL_HOSTNAME}
    port: ${MYSQL_PORT}
    database: ${MYSQL_DATABASE}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  campaign:
    hostname: ${CAMPAIGN_SERVICE_HOSTNAME}
    port: ${CAMPAIGN_SERVICE_PORT}
    resetTokenCampaignId: 1
  loki:
    url: ${LOKI_URL}
  cron:
    username: ${CRON_USERNAME}
    password: ${CRON_PASSWORD}

rptValidityInMinute: ${RPT_VALIDITY_IN_MINUTE}

frontend:
  gateway: ${FRONTEND_GATEWAY}

server:
  port: ${AUTH_SERVICE_PORT}

spring:
  jpa:
    openInView: false
    databasePlatform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddlAuto: update
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${service.mysql.hostname}:${service.mysql.port}/${service.mysql.database}?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: ${service.mysql.username}
    password: ${service.mysql.password}
  application:
    name: auth-service
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirectUri: ${GOOGLE_REDIRECT_URI}
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            redirectUri: ${FACEBOOK_REDIRECT_URI}
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirectUri: ${GITHUB_REDIRECT_URI}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${service.discovery.hostname}:${service.discovery.port}/eureka/
