queue:
  exchange: dev:amqp-exchange
  campaignQueue:
    name: dev:campaign-queue
    routingKey:
      all: dev:campaign.*
      addRecipient: dev:campaign.add-recipient
  userQueue:
    name: dev:user-queue
    routingKey:
      all: dev:user.*
      checkUserExist: dev:user.exist
      findUser: dev:user.find

loki:
    url: ${LOKI_URL}

server:
  port: ${SERVER_PORT}

spring:
  jpa:
    openInView: false
    databasePlatform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddlAuto: update
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_URL}?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  application:
    name: campaign-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVICE_URL}
  rabbitmq:
    host: host.docker.internal
    port: 5672

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URL}
