version: "3"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  broker:
    image: confluentinc/cp-kafka:latest
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  mysql-db:
    image: mysql:latest
    environment:
      TZ: Asia/Ho_Chi_Minh
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql_data

  discovery-service:
    image: duckervn/msult-discovery-service
    environment:
      SERVER_HOSTNAME: discovery-service
      SERVER_PORT: 8761
      LOKI_URL: http://host.docker.internal:3100
      DISCOVERY_SERVICE_URL: http://discovery-service:8761/eureka/
    ports:
      - "8761:8761"
    build:
      context: "./discovery-service"
      dockerfile: "Dockerfile"

  auth-service:
    image: duckervn/msult-auth-service
    environment:
      DISCOVERY_SERVICE_URL: http://discovery-service:8761/eureka/
      AUTH_SERVICE_URL: http://auth-service:8909
      MOVIE_SERVICE_URL: http://movie-service:8910
      MYSQL_URL: host.docker.internal:3306/ult_user
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      SERVER_PORT: 8909
      LOKI_URL: LOKI_URL
      GOOGLE_CLIENT_ID: GOOGLE_CLIENT_ID
      GOOGLE_CLIENT_SECRET: GOOGLE_CLIENT_SECRET
      GOOGLE_REDIRECT_URI: http://localhost:8909/login/oauth2/code/google
      FACEBOOK_CLIENT_ID: FACEBOOK_CLIENT_ID
      FACEBOOK_CLIENT_SECRET: FACEBOOK_CLIENT_SECRET
      FACEBOOK_REDIRECT_URI: http://localhost:8909/login/oauth2/code/facebook
      GITHUB_CLIENT_ID: GITHUB_CLIENT_ID
      GITHUB_CLIENT_SECRET: GITHUB_CLIENT_SECRET
      GITHUB_REDIRECT_URI: http://localhost:8909/login/oauth2/code/github
      FRONTEND_GATEWAY: http://localhost:3000
      CAMPAIGN_SERVICE_URL: http://campaign-service:8913
      CRON_USERNAME: CRON_USERNAME
      CRON_PASSWORD: CRON_PASSWORD
      RPT_CAMPAIGN_ID: 1
      RPT_VALIDITY_IN_MINUTE: 60
      KAFKA_BOOTSTRAP_SERVERS_URL: broker:9092
      KAFKA_CONSUMER_GROUP_ID: consumer-group
    ports:
      - "8909:8909"
    build:
      context: "./auth-service"
      dockerfile: "Dockerfile"
    depends_on:
      - mysql-db
      - discovery-service
      - broker

  movie-service:
    image: duckervn/msult-movie-service
    environment:
      DISCOVERY_SERVICE_URL: http://discovery-service:8761/eureka/
      AUTH_SERVICE_URL: http://auth-service:8909
      CAMPAIGN_SERVICE_URL: http://campaign-service:8913
      MYSQL_URL: host.docker.internal:3306/ult_movie
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      SERVER_PORT: 8910
      LOKI_URL: http://host.docker.internal:3100
      KAFKA_BOOTSTRAP_SERVERS_URL: broker:9092
      KAFKA_CONSUMER_GROUP_ID: consumer-group
    ports:
      - "8910:8910"
    build:
      context: "./movie-service"
      dockerfile: "Dockerfile"
    depends_on:
      - mysql-db
      - discovery-service
      - broker

  stream-service:
    image: duckervn/msult-stream-service
    environment:
      LOCAL_STORAGE: /mnt/files/
      DISCOVERY_SERVICE_URL: http://discovery-service:8761/eureka/
      AUTH_SERVICE_URL: http://auth-service:8909
      MOVIE_SERVICE_URL: http://movie-service:8910
      SERVER_PORT: 8911
      LOKI_URL: http://host.docker.internal:3100
      GATEWAY_URL: http://localhost:8762
      KAFKA_BOOTSTRAP_SERVERS_URL: broker:9092
      KAFKA_CONSUMER_GROUP_ID: consumer-group
    ports:
      - "8911:8911"
    build:
      context: "./stream-service"
      dockerfile: "Dockerfile"
    depends_on:
      - mysql-db
      - discovery-service
      - broker
    volumes:
      - store:/mnt/files

  cron-service:
    image: duckervn/msult-cron-service
    environment:
      DISCOVERY_SERVICE_URL: http://discovery-service:8761/eureka/
      AUTH_SERVICE_URL: http://auth-service:8909
      MOVIE_SERVICE_URL: http://movie-service:8910
      MYSQL_URL: host.docker.internal:3306/ult_schedule
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      SERVER_PORT: 8912
      LOKI_URL: http://host.docker.internal:3100
      CRON_USERNAME: CRON_USERNAME
      CRON_PASSWORD: CRON_PASSWORD
    ports:
      - "8912:8912"
    build:
      context: "./cron-service"
      dockerfile: "Dockerfile"
    depends_on:
      - mysql-db
      - discovery-service
      - broker

  campaign-service:
    image: duckervn/msult-campaign-service
    environment:
      DISCOVERY_SERVICE_URL: http://discovery-service:8761/eureka/
      AUTH_SERVICE_URL: http://auth-service:8909
      MOVIE_SERVICE_URL: http://movie-service:8910
      MYSQL_URL: host.docker.internal:3306/ult_campaign
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      SERVER_PORT: 8913
      LOKI_URL: http://host.docker.internal:3100
      FRONTEND_GATEWAY: http://localhost:3000
      KAFKA_BOOTSTRAP_SERVERS_URL: broker:9092
      KAFKA_CONSUMER_GROUP_ID: consumer-group
    ports:
      - "8913:8913"
    build:
      context: "./campaign-service"
      dockerfile: "Dockerfile"
    depends_on:
      - mysql-db
      - discovery-service
      - broker

  gate-service:
    image: duckervn/msult-gateway-service
    environment:
      DISCOVERY_SERVICE_URL: http://discovery-service:8761/eureka/
      AUTH_SERVICE_URL: http://auth-service:8909
      MOVIE_SERVICE_URL: http://movie-service:8910
      STREAM_SERVICE_URL: http://stream-service:8911
      CRON_SERVICE_URL: http://cron-service:8912
      CAMPAIGN_SERVICE_URL: http://campaign-service:8913
      SERVER_PORT: 8762
      LOKI_URL: http://host.docker.internal:3100
    ports:
      - "8762:8762"
    build:
      context: "./gateway-service"
      dockerfile: "Dockerfile"
    depends_on:
      - discovery-service

volumes:
  db:
  store:
