loki:
  url: ${LOKI_URL}

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: http://localhost:3000
            allowedHeaders: "*"
            allowedMethods: "*"
            allowCredentials: true
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL}
          predicates:
            - Path=/oauth2/**, /users/**, /login/**
        - id: movie-service
          uri: ${MOVIE_SERVICE_URL}
          predicates:
            - Path=/movies/**, /genres/**, /characters/**, /episodes/**, /producers/**
        - id: stream-service
          uri: ${STREAM_SERVICE_URL}
          predicates:
            - Path=/files/**
        - id: cron-service
          uri: ${CRON_SERVICE_URL}
          predicates:
            - Path=/schedules/**
        - id: campaign-service
          uri: ${CAMPAIGN_SERVICE_URL}
          predicates:
            - Path=/campaigns/**, /providers/**
        - id: activity-service
          uri: ${ACTIVITY_SERVICE_URL}
          predicates:
            - Path=/activities/**

server:
  port: ${SERVER_PORT}

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URL}
