loki:
  url: ${LOKI_URL}

spring:
  application:
    name: gateway-service
  cloud:
    loadbalancer:
      configurations: health-check
    gateway:
      httpclient:
        wiretap: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: ${FRONTEND_GATEWAY}
            allowedHeaders: "*"
            allowedMethods: "*"
            allowCredentials: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/oauth2/**, /users/**, /login/**
        - id: movie-service
          uri: lb://movie-service
          predicates:
            - Path=/movies/**, /genres/**, /characters/**, /episodes/**, /producers/**
        - id: stream-service
          uri: lb://stream-service
          predicates:
            - Path=/files/**, /cleaner/**
        - id: cron-service
          uri: lb://cron-service
          predicates:
            - Path=/schedules/**
        - id: campaign-service
          uri: lb://campaign-service
          predicates:
            - Path=/campaigns/**, /providers/**
        - id: activity-service
          uri: lb://activity-service
          predicates:
            - Path=/activities/**

server:
  port: ${SERVER_PORT}

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus,health

eureka:
  client:
    webclient:
      enabled: true
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URL}
    fetch-registry: true
    register-with-eureka: false
  instance:
    prefer-ip-address: true
