loki:
    url: ${LOKI_URL}

spring:
  application:
    name: discovery-service

server:
  port: ${SERVER_PORT}

eureka:
  instance:
    hostname: ${SERVER_HOSTNAME}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URL}
