loki:
    url: ${LOKI_URL}

spring:
  application:
    name: discovery-service

server:
  port: ${SERVER_PORT}

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus,health

eureka:
  instance:
    hostname: ${SERVER_HOSTNAME}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URL}
