spring:
  application:
    name: discovery

server:
  port: ${DISCOVERY_PORT}

eureka:
  instance:
    hostname: ${DISCOVERY_HOSTNAME}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
