root:
  location: ${LOCAL_STORAGE}

gateway:
  url: ${GATEWAY_URL}

server:
  port: ${SERVER_PORT}

loki:
  url: ${LOKI_URL}

spring:
  application:
    name: stream-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVICE_URL}

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URL}
