queue:
  exchange: dev:amqp-exchange
  movieQueue:
    name: dev:movie-queue
    routingKey:
      all: dev:movie.*
      storedFile: dev:movie.find-stored-file

loki:
  url: ${LOKI_URL}

server:
  port: ${SERVER_PORT}

spring:
  application:
    name: movie-service
  rabbitmq:
    host: host.docker.internal
    port: 5672
  jpa:
    openInView: false
    databasePlatform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddlAuto: update
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_URL}?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVICE_URL}

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URL}
